### ISSUE TITLE
1.13.0 Compat

### ISSUE THREAD

**Issue by tstirrat** [firebase/emberfire#267]
The plan for ED 1.13.x support:

- [x] ~~Get tests passing and things working correctly~~ #262 

**Deprecations:**
- [x] ~~The default behavior of `shouldBackgroundReloadRecord` will change in Ember Data 2.0 to always return true. If you would like to preserve the current behavior please override `shouldBackgroundReloadRecord` in you adapter:application and return false.~~ #280
- [x] ~~`store.push(type, data)` has been deprecated. Please provide a JSON-API document object as the first and only argument to `store.push`~~ #283
- [x] ~~Your custom serializer uses the old version of the Serializer API, with `extract` hooks. Please upgrade your serializers to the new Serializer API using `normalizeResponse` hooks instead~~ #283
- [x] ~~You provided an embedded option on the `p` property in the `X` class, this belongs in the serializer. See `DS.EmbeddedRecordsMixin` (This will require users to change they way they specify embedded record configs)~~ #283 
- [x] ~~`Ember.EnumerableUtils` is deprecated~~ #269 #275
- [x] ~~`Ember.keys` is deprecated in favor of `Object.keys`~~ #281

**Other general cleanup and legacy stuff:**
  - [x] ~~Use `snapshot` instead of `snapshot.record` where appropriate~~ #283 
  - [x] ~~Monkey patching of store.push fails when multiple records are pushed and and array is returned~~ #274 #283

**Comment by Ghostavio** [comment]
+1

**Comment by Ghostavio** [comment]
Just to know, what's the latest working version of Ember-Data for emberfire?

**Comment by tstirrat** [comment]
`1.4.7` works with `1.0.0-beta.18`
`master` works with `1.13.0+`

**Comment by stefanpenner** [comment]
worth noting, that without this canary/ 2.0.0 also will not work.

**Comment by ryanlitalien** [comment]
@tstirrat With merging of #283, could we get a release? Or should it stay on master until `adapter.recordWillDelete` is removed?

**Comment by tstirrat** [comment]
@ryanlitalien unfortunately there is still a bug with `hasMany` relationship saving (#287). Once I have that sorted I will get a release out.

**Comment by tstirrat** [comment]
ok, since closing #289 it looks like we are good for 1.13.0 compat

Just reviewing and updating docs for the release
